[package]
name = "memories"
version = "0.1.0"
edition = "2024"
authors = ["Raymond Finzel <rfinz.me@rfinz.me>"]

[dependencies]
zz = { path = "../zz" }
itertools = "0.14.0"
uuid = { version = "1.16.0", features = ["v4"] }
